"""Create initial tables

Revision ID: 410bfc120a39
Revises: 
Create Date: 2025-08-25 16:47:49.722724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410bfc120a39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('legal_person_tin', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('legal_person_tin'),
    sa.UniqueConstraint('legal_person_tin')
    )
    op.create_table('subscription',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('organization_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_tin', sa.String(length=255), nullable=False),
    sa.Column('subscription_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_tin'], ['organization.legal_person_tin'], ),
    sa.ForeignKeyConstraint(['subscription_name'], ['subscription.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_subscription')
    op.drop_table('subscription')
    op.drop_table('organization')
    # ### end Alembic commands ###
